name: pasaratsiri_app
description: "Aplikasi Pasar Atsiri, tempat untuk menemukan dan membeli minyak atsiri lokal terbaik."
publish_to: 'none'
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  local_auth: ^2.2.0
  image_picker: ^1.1.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  file_picker: ^8.0.5
  flutter_rating_bar: ^4.0.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
